# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    image_directory: '%kernel.project_dir%/public/uploads/images'
    stripeSK: "%env(STRIPE_SK)%"
    app.issuer: Insuria
    upload_directory: '%kernel.project_dir%/public/uploads'
    offre_images_directory: '%kernel.project_dir%/public/uploads/offres'
services:
 
    App\Entity\Reclamation:
        public: true

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $stripeSK: '%env(STRIPE_SK)%'
     
  

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose ID is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\MyGmailMailerService:
        arguments:
            $mailerConfig:
                host: 'smtp.gmail.com'
                port: 587
                username: 'rami.toubib2014@gmail.com'
                password: 'kngp embc okyp iodi'
                encryption: 'tls' # adjust based on your SMTP configuration
                fromAddress: 'rami.toubib2014@gmail.com'
                fromName: 'Insuria'            
mercuryseries_flashy:
        # The name to use as the flash message key in the session store
    flash_message_name:   mercuryseries_flashy_notification

        # The session store to use for storing flash messages
    session_store: null            

            
            

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

   